# Generated by Django 5.2.4 on 2026-03-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField(unique=True)),
                ('sistema', models.CharField(blank=True, max_length=100)),
                ('num_cicloe', models.CharField(blank=True, help_text='Número de cicloe-stación', max_length=50)),
                ('calle_prin', models.CharField(blank=True, help_text='Calle principal', max_length=255)),
                ('calle_secu', models.CharField(blank=True, help_text='Calle secundaria', max_length=255)),
                ('colonia', models.CharField(blank=True, max_length=255)),
                ('alcaldia', models.CharField(blank=True, max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('sitio_de_e', models.CharField(blank=True, help_text='Sitio de estación', max_length=255)),
                ('estatus', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cicloestación ECOBICI',
                'verbose_name_plural': 'Cicloestaciones ECOBICI',
                'ordering': ['alcaldia', 'num_cicloe'],
                'indexes': [models.Index(fields=['alcaldia'], name='ecobici_cic_alcaldi_1613d0_idx'), models.Index(fields=['estatus'], name='ecobici_cic_estatus_8e3f8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViajesDesglosados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField(unique=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('fecha_corte', models.DateField(blank=True, null=True)),
                ('hora', models.IntegerField(blank=True, help_text='Hora del día (0–23)', null=True)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('rango_edad', models.CharField(blank=True, max_length=50)),
                ('viajes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viajes Desglosados ECOBICI',
                'verbose_name_plural': 'Viajes Desglosados ECOBICI',
                'ordering': ['-fecha_corte', 'hora', 'genero'],
                'indexes': [models.Index(fields=['fecha_corte'], name='ecobici_via_fecha_c_c1e725_idx'), models.Index(fields=['genero'], name='ecobici_via_genero_004629_idx'), models.Index(fields=['anio', 'mes'], name='ecobici_via_anio_062ec0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViajesDiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField(unique=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('viajes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viajes Diarios ECOBICI',
                'verbose_name_plural': 'Viajes Diarios ECOBICI',
                'ordering': ['-fecha', 'genero'],
                'indexes': [models.Index(fields=['fecha'], name='ecobici_via_fecha_cf667e_idx'), models.Index(fields=['genero'], name='ecobici_via_genero_f74701_idx'), models.Index(fields=['anio', 'mes'], name='ecobici_via_anio_688fc0_idx')],
            },
        ),
    ]
