# Generated by Django 5.2.4 on 2026-03-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField(help_text='Campo _id de CKAN', unique=True)),
                ('gid', models.IntegerField(blank=True, null=True)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('cvegeo', models.CharField(blank=True, help_text='Clave geográfica censal', max_length=50)),
                ('cve_dleg', models.CharField(blank=True, help_text='Clave de alcaldía', max_length=10)),
                ('coun_left', models.IntegerField(blank=True, null=True)),
                ('coun_right', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colonia',
                'verbose_name_plural': 'Colonias',
                'ordering': ['nombre'],
            },
        ),
    ]
