# Generated by Django 5.2.4 on 2026-03-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('delegacion', models.CharField(blank=True, max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=255)),
                ('calle_y_numero', models.CharField(blank=True, max_length=255)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('uso_inmueble', models.CharField(blank=True, max_length=100)),
                ('cap_albergue', models.IntegerField(blank=True, help_text='Capacidad de albergue en personas', null=True)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refugio Temporal',
                'verbose_name_plural': 'Refugios Temporales',
                'ordering': ['delegacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RiesgoInundacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField(unique=True)),
                ('fenomeno', models.CharField(blank=True, max_length=100)),
                ('taxonomia', models.CharField(blank=True, max_length=100)),
                ('r_p_v_e', models.CharField(blank=True, help_text='Riesgo/Peligro/Vulnerabilidad/Exposición', max_length=50)),
                ('intensidad', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('cvegeo', models.CharField(blank=True, help_text='Clave geográfica AGEB', max_length=20)),
                ('alcaldia', models.CharField(blank=True, max_length=100)),
                ('entidad', models.CharField(blank=True, max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('perime_m', models.FloatField(blank=True, null=True)),
                ('period_ret', models.CharField(blank=True, help_text='Período de retorno', max_length=50)),
                ('intens_uni', models.CharField(blank=True, help_text='Unidad de intensidad', max_length=100)),
                ('intens_num', models.CharField(blank=True, help_text='Rango de intensidad', max_length=50)),
                ('int2', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Riesgo de Inundación',
                'verbose_name_plural': 'Riesgos de Inundación',
                'ordering': ['alcaldia', 'intensidad'],
                'indexes': [models.Index(fields=['alcaldia'], name='riesgos_rie_alcaldi_9562d6_idx'), models.Index(fields=['intensidad'], name='riesgos_rie_intensi_ba6522_idx'), models.Index(fields=['cvegeo'], name='riesgos_rie_cvegeo_505dc1_idx')],
            },
        ),
    ]
