# Generated by Django 5.2.4 on 2026-03-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField(unique=True)),
                ('id_estacion', models.CharField(help_text='Clave corta, e.g. BJU, MER', max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('alcaldia', models.CharField(blank=True, max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación de Monitoreo',
                'verbose_name_plural': 'Estaciones de Monitoreo',
                'ordering': ['alcaldia', 'nombre'],
                'indexes': [models.Index(fields=['alcaldia'], name='aire_estaci_alcaldi_46bbd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField(unique=True)),
                ('contaminante', models.CharField(blank=True, help_text='PM2.5, O3, CO, NO2, SO2…', max_length=20)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.IntegerField(blank=True, help_text='Hora del día (0–23)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='aire.estacion')),
            ],
            options={
                'verbose_name': 'Lectura de Calidad del Aire',
                'verbose_name_plural': 'Lecturas de Calidad del Aire',
                'ordering': ['-fecha', 'hora', 'contaminante'],
                'indexes': [models.Index(fields=['estacion', 'contaminante', 'fecha'], name='aire_lectur_estacio_8b4356_idx'), models.Index(fields=['contaminante'], name='aire_lectur_contami_831cd1_idx'), models.Index(fields=['fecha'], name='aire_lectur_fecha_b57d8b_idx')],
            },
        ),
    ]
