# Generated by Django 5.2.4 on 2026-03-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField(unique=True)),
                ('ao_hechos', models.CharField(blank=True, max_length=10)),
                ('mes_hechos', models.CharField(blank=True, max_length=20)),
                ('fecha_hecho', models.DateField(blank=True, null=True)),
                ('hora_hecho', models.CharField(blank=True, max_length=10)),
                ('ao_inicio', models.IntegerField(blank=True, null=True)),
                ('mes_inicio', models.CharField(blank=True, max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=10)),
                ('delito', models.CharField(max_length=255)),
                ('categoria_delito', models.CharField(blank=True, max_length=100)),
                ('fiscalia', models.CharField(blank=True, max_length=255)),
                ('agencia', models.CharField(blank=True, max_length=100)),
                ('unidad_investigacion', models.CharField(blank=True, max_length=100)),
                ('alcaldia_hechos', models.CharField(blank=True, max_length=100)),
                ('municipio_hechos', models.CharField(blank=True, max_length=100)),
                ('colonia_datos', models.CharField(blank=True, max_length=255)),
                ('fgj_colonia_registro', models.CharField(blank=True, max_length=255)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carpeta de Investigación',
                'verbose_name_plural': 'Carpetas de Investigación',
                'ordering': ['-fecha_hecho'],
                'indexes': [models.Index(fields=['categoria_delito'], name='seguridad_c_categor_70d5e6_idx'), models.Index(fields=['alcaldia_hechos'], name='seguridad_c_alcaldi_97ccec_idx'), models.Index(fields=['fecha_hecho'], name='seguridad_c_fecha_h_2f3ecb_idx')],
            },
        ),
    ]
