# Generated by Django 5.2.4 on 2026-03-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpetainvestigacion',
            name='alcaldia_catalogo',
            field=models.CharField(blank=True, help_text='Nuevo campo 2020+', max_length=100),
        ),
        migrations.AddField(
            model_name='carpetainvestigacion',
            name='competencia',
            field=models.CharField(blank=True, help_text='Nuevo campo 2020+', max_length=100),
        ),
    ]
