# Generated by Django 5.2.4 on 2026-03-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiniestroVial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField(unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_evento', models.CharField(blank=True, help_text='Colisión, atropellamiento, volcadura…', max_length=100)),
                ('alcaldia', models.CharField(blank=True, max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=255)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('vehiculos_involucrados', models.IntegerField(blank=True, null=True)),
                ('lesionados', models.IntegerField(blank=True, null=True)),
                ('fallecidos', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Siniestro Vial',
                'verbose_name_plural': 'Siniestros Viales',
                'ordering': ['-fecha', 'alcaldia'],
                'indexes': [models.Index(fields=['alcaldia', 'fecha', 'tipo_evento'], name='siniestros__alcaldi_84995e_idx'), models.Index(fields=['fecha'], name='siniestros__fecha_47df15_idx')],
            },
        ),
    ]
