# Generated by Django 5.2.4 on 2026-03-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfluenciaRTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('afluencia', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ckan_id', models.IntegerField(unique=True)),
                ('servicio', models.CharField(max_length=100)),
                ('tipo_pago', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Afluencia RTP',
                'verbose_name_plural': 'Afluencias RTP',
                'ordering': ['-fecha', 'servicio'],
            },
        ),
        migrations.CreateModel(
            name='AfluenciaMetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField()),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('afluencia', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('simple', 'Simple'), ('desglosada', 'Desglosada')], max_length=12)),
                ('linea', models.CharField(max_length=50)),
                ('estacion', models.CharField(max_length=100)),
                ('tipo_pago', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Afluencia Metro',
                'verbose_name_plural': 'Afluencias Metro',
                'ordering': ['-fecha', 'linea', 'estacion'],
                'unique_together': {('ckan_id', 'source')},
            },
        ),
        migrations.CreateModel(
            name='AfluenciaMetrobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField()),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('afluencia', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('simple', 'Simple'), ('desglosada', 'Desglosada')], max_length=12)),
                ('linea', models.CharField(max_length=50)),
                ('tipo_pago', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Afluencia Metrobús',
                'verbose_name_plural': 'Afluencias Metrobús',
                'ordering': ['-fecha', 'linea'],
                'unique_together': {('ckan_id', 'source')},
            },
        ),
        migrations.CreateModel(
            name='AfluenciaSTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckan_id', models.IntegerField()),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('afluencia', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sistema', models.CharField(choices=[('tren_ligero', 'Tren Ligero'), ('cablebus', 'Cablebus'), ('trolebus', 'Trolebús')], max_length=12)),
                ('linea', models.CharField(blank=True, max_length=50)),
                ('tipo_pago', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Afluencia STE',
                'verbose_name_plural': 'Afluencias STE',
                'ordering': ['-fecha', 'sistema'],
                'unique_together': {('ckan_id', 'sistema')},
            },
        ),
    ]
